using orm.attributes;
using orm.sql;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection;
using System.Text;
using ForeignKeyAttribute = orm.attributes.ForeignKeyAttribute;

namespace orm.ddl
{
    public static class DdlBuilder<T>
    {
        private static readonly NullabilityInfoContext NullCtx = new();

        public static string CreateTable()
        {
            var type = typeof(T);
            var tableName = Quote(type.Name);

            var properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance);
            if (properties.Length == 0)
                throw new InvalidOperationException($"Type {type.Name} has no public properties.");

            var columnLines = new List<string>();
            var primaryKey = new List<string>();
            var foreignKeys = new List<string>();
            var singleUnique = new List<string>();
            var uniqueGroups = new Dictionary<string, List<string>>(StringComparer.Ordinal);

            foreach (var p in properties)
            {
                if (IsNavigation(p)) continue;
                if (!SqlTypeHelper.TryGetSqlType(p, out var sqlType)) continue;

                var name = GetColumnName(p);
                var parts = new List<string> { Quote(name), sqlType };

                var isPk = p.GetCustomAttribute<PrimaryKeyAttribute>() != null;
                if (isPk) primaryKey.Add(Quote(name));

                var identity = p.GetCustomAttribute<IdentityAttribute>();
                if (identity != null)
                {
                    parts.Add(identity.Always
                        ? "GENERATED ALWAYS AS IDENTITY"
                        : "GENERATED BY DEFAULT AS IDENTITY");
                }
                else
                {
                    var notNull = isPk || p.GetCustomAttribute<RequiredAttribute>() != null || !IsNullable(p);
                    parts.Add(notNull ? "NOT NULL" : "NULL");
                }

                var def = p.GetCustomAttribute<DefaultAttribute>();
                if (def != null) parts.Add($"DEFAULT {def.ToSql()}");

                var uq = p.GetCustomAttribute<UniqueAttribute>();
                if (uq != null)
                {
                    if (string.IsNullOrWhiteSpace(uq.Group))
                        singleUnique.Add(name);
                    else
                    {
                        if (!uniqueGroups.TryGetValue(uq.Group, out var list))
                            uniqueGroups[uq.Group] = list = new List<string>();
                        list.Add(name);
                    }
                }

                columnLines.Add("    " + string.Join(" ", parts));

                var fk = p.GetCustomAttribute<ForeignKeyAttribute>();
                if (fk != null) foreignKeys.Add(BuildForeignKey(type.Name, name, fk));
            }

            var tableConstraints = new List<string>();

            if (primaryKey.Count > 0)
                tableConstraints.Add(
                    $"    CONSTRAINT {Quote($"PK_{type.Name}")} PRIMARY KEY ({string.Join(", ", primaryKey)})");

            foreach (var col in singleUnique)
                tableConstraints.Add(
                    $"    CONSTRAINT {Quote($"UQ_{type.Name}_{col}")} UNIQUE ({Quote(col)})");

            foreach (var g in uniqueGroups.OrderBy(g => g.Key, StringComparer.Ordinal))
                tableConstraints.Add(
                    $"    CONSTRAINT {Quote($"UQ_{type.Name}_{g.Key}")} UNIQUE ({string.Join(", ", g.Value.Select(Quote))})");

            tableConstraints.AddRange(foreignKeys);

            var body = string.Join(",\n", columnLines.Concat(tableConstraints));

            var sb = new StringBuilder();
            sb.AppendLine($"CREATE TABLE {tableName} (");
            sb.AppendLine(body);
            sb.AppendLine(");");
            return sb.ToString();
        }

        private static string BuildForeignKey(string tableName, string column, ForeignKeyAttribute fk)
        {
            var refTable = fk.References.Name;
            var refCol = string.IsNullOrWhiteSpace(fk.Column) ? "Id" : fk.Column;
            var name = $"FK_{tableName}_{refTable}_{column}";

            var sb = new StringBuilder(
                $"    CONSTRAINT {Quote(name)} FOREIGN KEY ({Quote(column)}) " +
                $"REFERENCES {Quote(refTable)} ({Quote(refCol)})");

            if (!string.IsNullOrWhiteSpace(fk.OnDelete)) sb.Append($" ON DELETE {fk.OnDelete!.ToUpperInvariant()}");
            if (!string.IsNullOrWhiteSpace(fk.OnUpdate)) sb.Append($" ON UPDATE {fk.OnUpdate!.ToUpperInvariant()}");

            return sb.ToString();
        }

        private static bool IsNavigation(PropertyInfo p)
        {
            if (p.GetCustomAttribute<HasManyAttribute>() != null) return true;
            if (p.GetCustomAttribute<HasOneAttribute>() != null) return true;

            var t = p.PropertyType;
            if (t != typeof(string) && t != typeof(byte[]) && typeof(IEnumerable).IsAssignableFrom(t))
                return true;

            return false;
        }

        private static bool IsNullable(PropertyInfo p)
        {
            var t = p.PropertyType;
            if (Nullable.GetUnderlyingType(t) != null) return true;
            if (t.IsValueType) return false;

            var info = NullCtx.Create(p);
            return info.WriteState == NullabilityState.Nullable
                || info.ReadState == NullabilityState.Nullable;
        }

        private static string GetColumnName(PropertyInfo p)
        {
            var col = p.GetCustomAttribute<ColumnAttribute>();
            return string.IsNullOrWhiteSpace(col?.Name) ? p.Name : col!.Name!;
        }

        private static string Quote(string identifier) => $"\"{identifier}\"";
    }
}
