using System;
using System.Collections.Generic;
using System.Linq;
using orm.data;
using orm.sql;

namespace orm.migrations
{
    public sealed class MigrationRunner
    {
        private const string HistoryTable = "__migrations";

        private readonly DbContext _session;

        public MigrationRunner(DbContext session)
        {
            _session = session;
            EnsureHistoryTable();
        }

        public List<SchemaChange> Pending(IEnumerable<Type> entities)
        {
            var current = DatabaseSchema.Read(_session);
            var applied = AppliedNames();

            return SchemaDiffer.Diff(entities, current)
                .Where(c => !applied.Contains(c.Name))
                .ToList();
        }

        public int Apply(IEnumerable<Type> entities)
        {
            var pending = Pending(entities);
            if (pending.Count == 0) return 0;

            _session.BeginTransaction();
            try
            {
                foreach (var change in pending)
                {
                    _session.Execute(change.Up);
                    _session.Execute(
                        $"INSERT INTO {Quoted(HistoryTable)} (\"Name\", \"Down\") " +
                        $"VALUES ({Literal(change.Name)}, {Literal(change.Down)})");
                }
                _session.Commit();
            }
            catch
            {
                _session.Rollback();
                throw;
            }

            return pending.Count;
        }

        public string? RevertLast()
        {
            var last = LastApplied();
            if (last == null) return null;

            Revert(last.Value.Name, last.Value.Down);
            return last.Value.Name;
        }

        private void Revert(string name, string down)
        {
            _session.BeginTransaction();
            try
            {
                _session.Execute(down);
                _session.Execute($"DELETE FROM {Quoted(HistoryTable)} WHERE \"Name\" = {Literal(name)}");
                _session.Commit();
            }
            catch
            {
                _session.Rollback();
                throw;
            }
        }

        private void EnsureHistoryTable() =>
            _session.Execute(
                $"CREATE TABLE IF NOT EXISTS {Quoted(HistoryTable)} (" +
                "\"Id\" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "\"Name\" TEXT NOT NULL UNIQUE, " +
                "\"Down\" TEXT NOT NULL, " +
                "\"AppliedAt\" TIMESTAMPTZ NOT NULL DEFAULT now())");

        private HashSet<string> AppliedNames()
        {
            var names = new HashSet<string>(StringComparer.Ordinal);
            using var reader = _session.ExecuteReader($"SELECT \"Name\" FROM {Quoted(HistoryTable)}");
            while (reader.Read())
                names.Add(reader.GetString(0));
            return names;
        }

        private (string Name, string Down)? LastApplied()
        {
            using var reader = _session.ExecuteReader(
                $"SELECT \"Name\", \"Down\" FROM {Quoted(HistoryTable)} ORDER BY \"Id\" DESC LIMIT 1");
            return reader.Read() ? (reader.GetString(0), reader.GetString(1)) : null;
        }

        private static string Quoted(string identifier) => EntityColumns.Quote(identifier);

        private static string Literal(string value) => SqlFormatHelper.GetSqlValue(value);
    }
}
