using orm.ddl;
using unittest.Models;

namespace unittest
{
    public class DdlBuilderTests
    {
        [Fact]
        public void CreateTable_StartsWithCreateTableStatement()
        {
            var sql = DdlBuilder<Company>.CreateTable();

            Assert.StartsWith("CREATE TABLE \"Company\" (", sql);
            Assert.EndsWith(");\r\n", sql);
        }

        [Fact]
        public void CreateTable_IdentityAlways_GeneratesAlwaysAsIdentity()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains("\"Id\" INTEGER GENERATED ALWAYS AS IDENTITY", sql);
        }

        [Fact]
        public void CreateTable_IdentityByDefault_GeneratesByDefaultAsIdentity()
        {
            var sql = DdlBuilder<Company>.CreateTable();

            Assert.Contains("\"Id\" INTEGER GENERATED BY DEFAULT AS IDENTITY", sql);
        }

        [Fact]
        public void CreateTable_RequiredProperty_IsNotNull()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains("\"Email\" TEXT NOT NULL", sql);
        }

        [Fact]
        public void CreateTable_NullableReferenceProperty_IsNull()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains("\"Nickname\" TEXT NULL", sql);
        }

        [Fact]
        public void CreateTable_NonNullableReferenceProperty_IsNotNull()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains("\"FirstName\" TEXT NOT NULL", sql);
            Assert.Contains("\"LastName\" TEXT NOT NULL", sql);
        }

        [Fact]
        public void CreateTable_DefaultAttribute_AppendsDefaultClause()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains("\"Status\" TEXT NOT NULL DEFAULT 'active'", sql);
        }

        [Fact]
        public void CreateTable_PrimaryKey_AddsPrimaryKeyConstraint()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains("CONSTRAINT \"PK_User\" PRIMARY KEY (\"Id\")", sql);
        }

        [Fact]
        public void CreateTable_NoPrimaryKey_OmitsPrimaryKeyConstraint()
        {
            var sql = DdlBuilder<LogEntry>.CreateTable();

            Assert.DoesNotContain("PRIMARY KEY", sql);
            Assert.Contains("\"Message\" TEXT NOT NULL", sql);
        }

        [Fact]
        public void CreateTable_SingleUnique_AddsUniqueConstraint()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains("CONSTRAINT \"UQ_User_Email\" UNIQUE (\"Email\")", sql);
        }

        [Fact]
        public void CreateTable_UniqueGroup_AddsCompositeUniqueConstraint()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains("CONSTRAINT \"UQ_User_FullName\" UNIQUE (\"FirstName\", \"LastName\")", sql);
        }

        [Fact]
        public void CreateTable_ForeignKey_AddsForeignKeyConstraintWithOnDelete()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.Contains(
                "CONSTRAINT \"FK_User_Company_CompanyId\" FOREIGN KEY (\"CompanyId\") REFERENCES \"Company\" (\"Id\") ON DELETE CASCADE",
                sql);
        }

        [Fact]
        public void CreateTable_HasManyNavigation_IsExcludedFromColumns()
        {
            var sql = DdlBuilder<User>.CreateTable();

            Assert.DoesNotContain("Orders", sql);
        }

        [Fact]
        public void CreateTable_ColumnAttribute_OverridesColumnName()
        {
            var sql = DdlBuilder<CustomColumnEntity>.CreateTable();

            Assert.Contains("\"user_email\" TEXT NOT NULL", sql);
            Assert.DoesNotContain("\"Email\"", sql);
        }

        [Fact]
        public void CreateTable_NoProperties_Throws()
        {
            Assert.Throws<InvalidOperationException>(() => DdlBuilder<EmptyEntity>.CreateTable());
        }
    }
}
